version: "3.1"
services:
  db:
    image: postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin4
      POSTGRES_DB: my-expenses
      POSTGRES_USER: postgres
